Functions and exceptions
-----------------------
def greet():
    print('Hello, my dear')
greet()
Output: Hello, my dear

input_numbers = [5.0, 6.3, 5.1, 9.9, 10.0]
sum = 0
for number in input_numbers:
    sum += number
average = sum / len(input_numbers)
print(average)
output: 7.26

def get_average(input_numbers):   # parameter given to the function
    sum = 0.0
    for number in input_numbers:
        sum += number
    average = sum / len(input_numbers)
    print(average)
get_average([5.0, 3.5, 7.8, 9.9, 10.0])    # the list passed to the function is called an argument
output: 7.24
